from __future__ import annotations

import html
import smtplib
from email.message import EmailMessage

from .config import Settings, load_settings
from .models import NewsletterIssue
from .presentation import (
    build_intelligence_sections,
    canonical_source_type,
    compute_issue_metrics,
    display_event_coverage,
    display_factual_summary_en,
    display_factual_summary_ko,
    display_primary_category,
    display_published_time,
    display_summary_en,
    display_summary_ko,
    display_title_en,
    display_title_ko,
    display_url,
    display_why_it_matters_en,
    display_why_it_matters_ko,
    regions_for_article,
    visible_tags,
)
from .priority import assess_priority


class MailConfigError(RuntimeError):
    pass


PRIORITY_COLORS = {
    "critical": {"solid": "#dc2626", "soft": "#fef2f2", "text": "#991b1b"},
    "high": {"solid": "#ea580c", "soft": "#fff7ed", "text": "#9a3412"},
    "medium": {"solid": "#2563eb", "soft": "#eff6ff", "text": "#1e40af"},
    "watch": {"solid": "#64748b", "soft": "#f8fafc", "text": "#334155"},
}


def build_email_html(issue: NewsletterIssue, lang: str = "ko") -> str:
    sections = _email_sections(issue, lang=lang)
    metrics = compute_issue_metrics(sections)
    is_en = lang == "en"

    preheader = (
        f"{issue.issue_date} AI Intelligence Briefing — Total {metrics['total']}, Critical {metrics['critical']}"
    ) if is_en else (
        f"{issue.issue_date} AI 산업 핵심 인텔리전스 — 총 {metrics['total']}건, 최우선 {metrics['critical']}건"
    )

    title_text = "AI Industry & Frontier Briefing" if is_en else "AI 산업 핵심 인텔리전스 브리핑"
    subtitle_text = (
        "Curated briefing on Frontier LLMs, Agents, AI Chips, Infrastructure, and Regulations."
        if is_en
        else "프론티어 LLM, 자율 에이전트, AI 반도체, 오픈소스 및 정책 동향을 우선순위 중심으로 정리했습니다."
    )
    warnings_title = "Collection Notes" if is_en else "수집 참고"

    parts = [
        f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>AI Intelligence Brief</title></head>",
        '<body style="margin:0;padding:0;background-color:#f8fafc;color:#0f172a;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Helvetica,Arial,sans-serif;">',
        f'<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">{html.escape(preheader)}</div>',
        '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#f8fafc;padding:32px 0;">',
        '<tr><td align="center" style="padding:0 16px;">',
        '<table role="presentation" width="700" cellspacing="0" cellpadding="0" style="width:100%;max-width:700px;border-collapse:separate;border-spacing:0;">',
        '<tr><td style="background:linear-gradient(135deg,#0f172a 0%,#1e1b4b 100%);color:#ffffff;padding:32px 32px 28px;border-radius:12px 12px 0 0;">',
        '<div style="font-size:12px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#818cf8;">AI Newsletter & Intelligence</div>',
        f'<h1 style="margin:8px 0 10px;font-size:26px;line-height:1.25;font-weight:800;color:#ffffff;">{html.escape(issue.issue_date)} {title_text}</h1>',
        f'<p style="margin:0;font-size:14px;line-height:1.6;color:#cbd5e1;">{subtitle_text}</p>',
        "</td></tr>",
        '<tr><td style="background-color:#ffffff;padding:28px 32px 36px;border-radius:0 0 12px 12px;border:1px solid #e2e8f0;border-top:0;">',
        '<h2 style="margin:0 0 14px;font-size:16px;font-weight:700;color:#0f172a;text-transform:uppercase;letter-spacing:0.5px;">Executive Snapshot</h2>',
        _metric_table(metrics, lang=lang),
    ]

    for _, label, articles in sections:
        if not articles:
            continue
        parts.append(
            f'<h2 style="margin:32px 0 14px;font-size:19px;font-weight:700;color:#0f172a;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">{html.escape(label)}</h2>'
        )
        for article in articles:
            parts.append(_article_card_html(article, lang=lang))

    if issue.warnings:
        parts.append(
            f'<h2 style="margin:32px 0 12px;font-size:18px;line-height:1.3;color:#0f172a;">{warnings_title}</h2>'
        )
        for warning in issue.warnings:
            parts.append(
                '<p style="margin:0 0 8px;padding:12px 14px;border:1px solid #fed7aa;border-radius:8px;background-color:#fff7ed;color:#9a3412;font-size:13px;line-height:1.55;">'
                f"{html.escape(warning)}</p>"
            )

    footer_text = (
        "Generated by AI Newsletter & Intelligence Platform. Click original buttons to view source publications."
        if is_en
        else "본 메일은 AI Newsletter 플랫폼에서 자동 생성되었습니다. 원문 링크를 통해 세부 기사를 확인하실 수 있습니다."
    )
    parts.extend(
        [
            '<div style="margin-top:36px;padding-top:20px;border-top:1px solid #e2e8f0;color:#64748b;font-size:12px;line-height:1.6;">',
            f"{footer_text}",
            "</div>",
            "</td></tr></table></td></tr></table></body></html>",
        ]
    )
    return "".join(parts)


def build_email_text(issue: NewsletterIssue, lang: str = "ko") -> str:
    sections = _email_sections(issue, lang=lang)
    metrics = compute_issue_metrics(sections)
    is_en = lang == "en"

    lines = [
        f"AI Intelligence Briefing - {issue.issue_date}",
        (
            f"Total News: {metrics['total']} / Critical: {metrics['critical']} / High: {metrics['high']}"
        ) if is_en else (
            f"총 브리핑: {metrics['total']}건 / 최우선 뉴스: {metrics['critical']}건 / 높음: {metrics['high']}건"
        ),
        "",
    ]
    for _, label, articles in sections:
        if not articles:
            continue
        lines.append(f"=== {label} ===")
        for article in articles:
            priority = assess_priority(article)
            p_label = priority.label_en if is_en else priority.label_ko
            title = display_title_en(article) if is_en else display_title_ko(article)
            reason = priority.reason_en if is_en else priority.reason_ko
            summary = display_summary_en(article) if is_en else display_summary_ko(article)
            why_text = display_why_it_matters_en(article) if is_en else display_why_it_matters_ko(article)
            publisher = article.publisher or article.source

            lines.append(f"[{p_label}] {title}")
            lines.append(f"  출처: {publisher} | 점수: {priority.score} ({reason})")
            lines.append(f"  요약: {summary}")
            if why_text:
                lines.append(f"  시사점: {why_text}")
            lines.append(f"  원문: {display_url(article)}")
            lines.append("")
        lines.append("")
    return "\n".join(lines)


def send_issue(issue: NewsletterIssue, settings: Settings | None = None, lang: str = "ko") -> None:
    settings = settings or load_settings()
    missing = settings.missing_smtp_fields()
    if missing:
        raise MailConfigError(f"메일 발송 설정이 부족합니다: {', '.join(missing)}")

    is_en = lang == "en"
    subject = (
        f"[AI Briefing] {issue.issue_date} | Frontier Models, Chips & Agents"
        if is_en
        else f"[AI 브리핑] {issue.issue_date} | LLM·반도체·에이전트 인텔리전스"
    )

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = settings.smtp_from or ""
    message["To"] = ", ".join(settings.recipients)
    message.set_content(build_email_text(issue, lang=lang))
    message.add_alternative(build_email_html(issue, lang=lang), subtype="html")

    try:
        with smtplib.SMTP(settings.smtp_host or "", settings.smtp_port, timeout=20) as smtp:
            if settings.smtp_tls:
                smtp.starttls()
            if settings.smtp_user and settings.smtp_password:
                smtp.login(settings.smtp_user, settings.smtp_password)
            smtp.send_message(message)
    except (smtplib.SMTPException, OSError) as exc:
        raise MailConfigError(f"메일 발송에 실패했습니다: {exc}") from exc


def _email_sections(issue: NewsletterIssue, lang: str = "ko") -> list[tuple[str, str, list]]:
    intel_sections = build_intelligence_sections(issue, lang=lang)
    return [
        (str(sec["key"]), str(sec["label"]), list(sec["articles"]))
        for sec in intel_sections
        if sec["articles"]
    ]


def _metric_table(metrics: dict[str, int], lang: str = "ko") -> str:
    is_en = lang == "en"
    cells = [
        ("Total News" if is_en else "총 브리핑", metrics["total"], "#0f172a"),
        ("Critical" if is_en else "최우선 뉴스", metrics["critical"], "#dc2626"),
        ("High" if is_en else "높음", metrics["high"], "#ea580c"),
    ]
    rendered = []
    for label, value, color in cells:
        rendered.append(
            '<td width="33%" style="padding:0 8px 8px 0;">'
            f'<div style="background-color:#f1f5f9;border-radius:8px;padding:12px 14px;border-left:4px solid {color};">'
            f'<div style="font-size:11px;font-weight:700;text-transform:uppercase;color:#64748b;">{html.escape(label)}</div>'
            f'<div style="font-size:22px;font-weight:800;color:#0f172a;margin-top:4px;">{value}</div>'
            "</div></td>"
        )
    return (
        '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-bottom:20px;">'
        f"<tr>{''.join(rendered)}</tr></table>"
    )


def _article_card_html(article, lang: str = "ko") -> str:
    is_en = lang == "en"
    priority = assess_priority(article)
    theme = PRIORITY_COLORS.get(priority.level, PRIORITY_COLORS["watch"])

    title = display_title_en(article) if is_en else display_title_ko(article)
    summary = display_factual_summary_en(article) if is_en else display_factual_summary_ko(article)
    why_text = display_why_it_matters_en(article) if is_en else display_why_it_matters_ko(article)
    why_label = "Strategic Impact" if is_en else "산업 시사점"
    source_url = display_url(article)
    publisher = article.publisher or article.source or "Source"

    coverage = display_event_coverage(article)
    coverage_badge = ""
    if coverage and coverage.get("source_count", 1) > 1:
        c_label = coverage["label_en"] if is_en else coverage["label_ko"]
        coverage_badge = (
            f'<span style="background-color:#e0e7ff;color:#3730a3;font-size:11px;font-weight:600;padding:2px 8px;border-radius:4px;margin-left:6px;">'
            f"{html.escape(c_label)}</span>"
        )

    return f"""
    <div style="background-color:#ffffff;border:1px solid #e2e8f0;border-radius:8px;padding:18px 20px;margin-bottom:14px;">
      <div style="margin-bottom:8px;">
        <span style="background-color:{theme['soft']};color:{theme['text']};border:1px solid {theme['solid']};font-size:11px;font-weight:700;padding:2px 8px;border-radius:4px;">
          {html.escape(priority.label_en if is_en else priority.label_ko)} ({priority.score})
        </span>
        <span style="color:#64748b;font-size:12px;margin-left:8px;">{html.escape(publisher)}</span>
        {coverage_badge}
      </div>
      <h3 style="margin:0 0 8px;font-size:16px;line-height:1.4;font-weight:700;color:#0f172a;">
        <a href="{html.escape(source_url)}" style="color:#0f172a;text-decoration:none;" target="_blank">
          {html.escape(title)}
        </a>
      </h3>
      <p style="margin:0 0 10px;font-size:13px;line-height:1.6;color:#334155;">
        {html.escape(summary)}
      </p>
      {f'<div style="background-color:#f8fafc;border-left:3px solid #6366f1;padding:8px 12px;font-size:12px;line-height:1.5;color:#475569;margin-bottom:10px;"><strong>{why_label}:</strong> {html.escape(why_text)}</div>' if why_text else ''}
      <div style="font-size:12px;color:#64748b;">
        <a href="{html.escape(source_url)}" style="color:#4f46e5;text-decoration:none;font-weight:600;" target="_blank">
          {'Read Original Article →' if is_en else '원문 기사 보기 →'}
        </a>
      </div>
    </div>
    """

